language: rust
rust:
  - beta
  - nightly
cache: cargo
env:
- MCU=stm32f756
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - rustup target add thumbv7em-none-eabihf
  - cargo build --features=$MCU
