language: rust
rust:
  - beta
  - nightly
cache: cargo
env:
- MCU=stm32f7x2
- MCU=stm32f7x3
- MCU=stm32f7x5
- MCU=stm32f7x6
- MCU=stm32f7x7
- MCU=stm32f7x9
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - rustup target add thumbv7em-none-eabihf
  - cargo build --features=$MCU
